### PR TITLE
Added animation for status bar

### PR DESCRIPTION
**Pull request by christoph-fricke**
Status bar will appear in style.

### CODE REVIEW

**Review by bendixsonnenberg — CHANGES_REQUESTED** [review]
dont use window.scroll
it will just eat processing power like americans fat
use the 'didscroll' variable
set an interval and check that boolean 
also it doesnt work in firefox

**Comment by bendixsonnenberg** [comment]
i just found out that i just had to scroll past the bars for them to change
bad placement of triggers

**Comment by christoph-fricke** [comment]
@quannten24 The trigger is working just fine for me... It is getting triggered as soon as the container is reaching half of the height of the window... What is not working for you?

**Review by bendixsonnenberg — APPROVED** [review]

**Comment by bendixsonnenberg** [comment]
after you switched to less processor intensiv calculations it worked

**Comment by christoph-fricke** [comment]
Your computer is just to bad to handle the power of this amazing website... xD

**Pull request merged**
